WIP global: admin UI first draft
inveniosoftware-attic/invenio-circulation-legacy pull request #39
Opened 2016-09-20 09:18 UTC by mvesper

* Uses invenio-search-js to add the search functionality.

2016-09-20 09:39 UTC, jirikuncar commented on invenio_circulation/bundles.py
>      filters='jsmin',
maybe you need `requirejs` filter instead of including `require.js`

2016-09-20 09:41 UTC, jirikuncar commented on invenio_circulation/bundles.py
> +    'js/circulation/circulation.module.js',
why did you rename it from `app.js`?

2016-09-20 13:06 UTC, jirikuncar commented on invenio_circulation/templates/invenio_circulation/index.html
> +     placeholder="{{ _('My Uploads') }}">
My Uploads?

2016-09-20 13:06 UTC, jirikuncar commented on invenio_circulation/templates/invenio_circulation/index.html
> +
can you remove empty lines that are not needed?

2016-09-20 13:07 UTC, jirikuncar commented on invenio_circulation/static/js/circulation/app.js
> +    'node_modules/angular/angular.js',
Do we need `.js`?

2016-09-20 13:07 UTC, jirikuncar requested changes

2016-09-20 14:00 UTC, mvesper commented on invenio_circulation/static/js/circulation/app.js
> +    'node_modules/angular/angular.js',
Seems to be necessary :/

2016-09-20 14:01 UTC, mvesper commented on invenio_circulation/templates/invenio_circulation/index.html
> +     placeholder="{{ _('My Uploads') }}">
Fixed

2016-09-20 14:01 UTC, mvesper commented on invenio_circulation/templates/invenio_circulation/index.html
> +
Fixed

2016-09-20 14:03 UTC, jirikuncar approved these changes

2016-09-28 09:22 UTC, jirikuncar requested changes

2016-09-28 09:22 UTC, jirikuncar commented on invenio_circulation/views/ui.py
> +                           config=current_app.config)
this should be available by default

2016-09-28 09:25 UTC, mvesper commented on invenio_circulation/views/ui.py
> +                           config=current_app.config)
Indeed :)

2016-09-28 09:37 UTC, jirikuncar approved these changes

2016-09-28 09:42 UTC, merged