WIP global: admin UI first draft
inveniosoftware-attic/invenio-circulation-legacy pull request #41
Opened 2016-09-29 13:38 UTC by mvesper

* Uses angular-ui typeahead to implement the circulation user search.

2016-09-29 13:43 UTC, jirikuncar requested changes

2016-09-29 13:43 UTC, jirikuncar commented on invenio_circulation/static/js/circulation/circulationUserSearch.directive.js
> +(function (angular) {
missing license header

2016-09-29 13:43 UTC, jirikuncar commented on invenio_circulation/static/templates/invenio_circulation/typeahead-popup.html
> +    <li class="uib-typeahead-match" ng-repeat="match in matches track by $index" ng-class="{active: isActive($index) }" ng-mouseenter="selectActive($index)" ng-click="selectMatch($index, $event)" rol
2 vs. 4 space indentation? IMHO we use 2 spaces for templates

2016-09-29 13:49 UTC, mvesper commented on invenio_circulation/static/js/circulation/circulationUserSearch.directive.js
> +(function (angular) {
Fixed

2016-09-29 13:49 UTC, mvesper commented on invenio_circulation/static/templates/invenio_circulation/typeahead-popup.html
> +    <li class="uib-typeahead-match" ng-repeat="match in matches track by $index" ng-class="{active: isActive($index) }" ng-mouseenter="selectActive($index)" ng-click="selectMatch($index, $event)" rol
Fixed

2016-10-03 12:04 UTC, drjova commented on invenio_circulation/static/js/circulation/circulationUserSearch.directive.js
> +      templateUrl: 'static/templates/invenio_circulation/circulation-user-search.html',
hmm, why not to use our configurable way? 

```js
function templateUrl(element, attrs) {
  return attrs.template;
}

////////////

return {
   templateUrl: templateUrl,
};
```

this way you can choose the template like

```html
<circulation-user-search template="blalba.hml">

</circulation-user-search>
```

2016-10-03 12:04 UTC, drjova commented on invenio_circulation/static/js/circulation/circulationUserSearch.directive.js
> +      scope.selected = undefined;
by default ``scope.selected`` is ``undefined`` you don't need to specify that :)

2016-10-03 12:04 UTC, drjova commented on setup.py
> +    'flask-wtf<0.13',
IMHO should be ``>=0.13``

2016-10-03 12:04 UTC, drjova commented on invenio_circulation/bundles.py
> +        'angular-ui-bootstrap': '~2.1.4',
It would be better if you can separate the dependencies from the actual app, please have a look here https://github.com/inveniosoftware/invenio-deposit/blob/master/invenio_deposit/bundles.py

2016-10-03 14:12 UTC, mvesper commented on invenio_circulation/static/js/circulation/circulationUserSearch.directive.js
> +      templateUrl: 'static/templates/invenio_circulation/circulation-user-search.html',
Changed

2016-10-03 14:14 UTC, mvesper commented on invenio_circulation/static/js/circulation/circulationUserSearch.directive.js
> +      scope.selected = undefined;
Changed

2016-10-03 14:18 UTC, mvesper commented on setup.py
> +    'flask-wtf<0.13',
That was only a temporary workaround

2016-10-03 14:18 UTC, mvesper commented on invenio_circulation/bundles.py
> +        'angular-ui-bootstrap': '~2.1.4',
I propose that I do this in another PR to keep this one clean :)

2016-10-03 14:28 UTC, jirikuncar commented on setup.py
> +    'flask-wtf<0.13',
I have released Invenio-Accounts, Invenio-OAuth2Server, and Invenio-Webhooks so it should not be necessary anymore. Just bump the packages mentioned earlier. Thanks!

2016-10-03 14:30 UTC, jirikuncar approved these changes

2016-10-03 14:45 UTC, merged