WIP global: admin UI first draft
inveniosoftware-attic/invenio-circulation-legacy pull request #43
Opened 2016-10-11 10:43 UTC by mvesper

* Adds a 'basket' to store found items before running a circulation
  command on those items and the selected user.

2016-10-11 11:17 UTC, drjova requested changes

2016-10-11 11:17 UTC, drjova commented on invenio_circulation/static/js/circulation/directives/circulationItemBasket.js
> +      console.log(data);
Could you please remove the the ```console.log```?

2016-10-11 11:17 UTC, drjova commented on invenio_circulation/static/js/circulation/directives/circulationItemBasket.js
> +          console.log('Success');
What about trigger an alert to notify the user?

2016-10-11 11:17 UTC, drjova commented on invenio_circulation/static/js/circulation/directives/circulationItemBasket.js
> +          console.log('Failure');
ditto

2016-10-11 11:17 UTC, drjova commented on invenio_circulation/static/js/circulation/factories/circulationItemBasket.js
> +  circulationItemStore.$inject = [];
you can remove this :)

2016-10-11 11:17 UTC, drjova commented on invenio_circulation/static/js/circulation/factories/circulationUserStore.js
> +  circulationUserStore.$inject = [];
you can remove this :)

2016-10-11 11:17 UTC, drjova commented on invenio_circulation/static/js/circulation/directives/circulationAddItem.js
> +  circulationAddItem.$inject = ['circulationItemStore']
semicolon missing?

2016-10-11 11:17 UTC, drjova commented on invenio_circulation/static/js/circulation/directives/circulationItemBasket.js
> +      angular.forEach(circulationItemStore.items, function(item, index) {
maybe we need a ```throttle``` here? If there are many ```items``` it might affect the server?

2016-10-12 08:35 UTC, mvesper commented on invenio_circulation/static/js/circulation/directives/circulationItemBasket.js
> +      console.log(data);
Removed :)

2016-10-12 08:35 UTC, mvesper commented on invenio_circulation/static/js/circulation/directives/circulationItemBasket.js
> +          console.log('Failure');
Removed :)

2016-10-12 08:35 UTC, mvesper commented on invenio_circulation/static/js/circulation/factories/circulationItemBasket.js
> +  circulationItemStore.$inject = [];
Removed :)

2016-10-12 08:35 UTC, mvesper commented on invenio_circulation/static/js/circulation/directives/circulationAddItem.js
> +  circulationAddItem.$inject = ['circulationItemStore']
Yep ^^

2016-10-12 08:35 UTC, mvesper commented on invenio_circulation/static/js/circulation/factories/circulationUserStore.js
> +  circulationUserStore.$inject = [];
Removed :)

2016-10-12 08:36 UTC, mvesper commented on invenio_circulation/static/js/circulation/directives/circulationItemBasket.js
> +          console.log('Success');
I propose to add features like in a later PR to keep this one smaller

2016-10-12 08:37 UTC, mvesper commented on invenio_circulation/static/js/circulation/directives/circulationItemBasket.js
> +      angular.forEach(circulationItemStore.items, function(item, index) {
It seems quite unlikely to ever work on enough items to make a throttle necessary. But maybe in the future :)

2016-10-12 09:29 UTC, jirikuncar commented on invenio_circulation/templates/invenio_circulation/index.html
> +   loan-endpoint="'/hooks/receivers/circulation_loan/events/'"
- Do you need both quotes - `"'`?
- Maybe we should make them configurable (missing `/api` prefix)?

2016-10-12 09:44 UTC, mvesper commented on invenio_circulation/templates/invenio_circulation/index.html
> +   loan-endpoint="'/hooks/receivers/circulation_loan/events/'"
* The `"'` seems to be necessary, otherwise angular tries to evaluate it
* I moved the URLs to `invenio_circulation.config` (and the `/api` prefix is not missing right now)

2016-10-12 09:45 UTC, jirikuncar commented on invenio_circulation/templates/invenio_circulation/index.html
> +   loan-endpoint="'/hooks/receivers/circulation_loan/events/'"
That's weird. Any reason why angular should evaluate it? cc @drjova

2016-10-12 11:12 UTC, drjova commented on invenio_circulation/static/js/circulation/directives/circulationItemBasket.js
> +        performAction(scope.requestEndpoint, data);
```attributes.requestEndpoint```

2016-10-12 11:12 UTC, drjova commented on invenio_circulation/static/js/circulation/directives/circulationItemBasket.js
> +        performAction(scope.loanEndpoint, data);
shouldn't be ```attributes.loanEndpoint``` ?

2016-10-12 11:14 UTC, drjova commented on invenio_circulation/templates/invenio_circulation/index.html
> +   loan-endpoint="'/hooks/receivers/circulation_loan/events/'"
Hmm I think you don't need that https://github.com/inveniosoftware/invenio-deposit/blob/master/invenio_deposit/templates/invenio_deposit/edit.html#L69 . Please have a look on https://github.com/inveniosoftware/invenio-circulation/pull/43#pullrequestreview-3852501


In general the ``"'`` is used for ```ng-include``` ```src``` https://docs.angularjs.org/api/ng/directive/ngInclude

2016-10-12 13:14 UTC, mvesper commented on invenio_circulation/templates/invenio_circulation/index.html
> +   loan-endpoint="'/hooks/receivers/circulation_loan/events/'"
I moved those three attributes out of the directives scope, so now I don't need `"'`

2016-10-12 13:15 UTC, mvesper commented on invenio_circulation/static/js/circulation/directives/circulationItemBasket.js
> +        performAction(scope.requestEndpoint, data);
Adjusted

2016-10-12 13:15 UTC, mvesper commented on invenio_circulation/static/js/circulation/directives/circulationItemBasket.js
> +        performAction(scope.loanEndpoint, data);
Adjusted

2016-10-12 13:58 UTC, jirikuncar commented on invenio_circulation/config.py
> +CIRCULATION_ACTION_LOAN_URL = '/hooks/receivers/circulation_loan/events/'
IMHO the default should be with `/api` prefix

2016-10-12 14:01 UTC, drjova commented on invenio_circulation/static/js/circulation/directives/circulationItemBasket.js
> +        }).then(function (response) {
it's a bit weird to have anonymous empty functions, it'd be better to remove the `then` and add it when it's needed :)

2016-10-12 14:04 UTC, drjova commented on invenio_circulation/static/js/circulation/factories/circulationItemStore.js
> +    }
``;``

2016-10-12 14:04 UTC, drjova commented on invenio_circulation/static/js/circulation/factories/circulationUserStore.js
> +    }
``;``

2016-10-12 14:04 UTC, drjova commented on invenio_circulation/static/templates/invenio_circulation/results.html
> +    <h5>{{ record.metadata.control_number }}: {{ record.metadata.title_statement.title }}</h5><circulation-add-item item="record" template="static/templates/invenio_circulation/circulation-add-item.h
maybe it's a bit cleaner to add the ```circulation-add-item``` in a new line?

2016-10-12 14:10 UTC, mvesper commented on invenio_circulation/static/js/circulation/directives/circulationItemBasket.js
> +        }).then(function (response) {
Changed

2016-10-12 14:10 UTC, mvesper commented on invenio_circulation/static/js/circulation/factories/circulationItemStore.js
> +    }
Added

2016-10-12 14:10 UTC, mvesper commented on invenio_circulation/static/js/circulation/factories/circulationUserStore.js
> +    }
Added

2016-10-12 14:10 UTC, mvesper commented on invenio_circulation/static/templates/invenio_circulation/results.html
> +    <h5>{{ record.metadata.control_number }}: {{ record.metadata.title_statement.title }}</h5><circulation-add-item item="record" template="static/templates/invenio_circulation/circulation-add-item.h
Changed

2016-10-12 14:11 UTC, drjova approved these changes

2016-10-12 15:01 UTC, mvesper commented on invenio_circulation/config.py
> +CIRCULATION_ACTION_LOAN_URL = '/hooks/receivers/circulation_loan/events/'
Changed :)

2016-10-20 12:56 UTC, merged