WIP global: user hub UI
inveniosoftware-attic/invenio-circulation-legacy pull request #59
Opened 2016-11-07 16:36 UTC by mvesper

* Adds the first implementation of the 'user hub' user interface.

2016-11-07 16:48 UTC, jirikuncar commented
@mvesper can you mark strings for translations in Angular templates with `translate` attribute? (see  e.g. https://github.com/inveniosoftware/invenio-search-ui/pull/40/files#diff-63ef883cfeb6fb0541e35aa985bb9b6dR3)

2016-11-08 12:34 UTC, drjova requested changes

2016-11-08 12:34 UTC, drjova commented on invenio_circulation/static/js/circulation/user_hub_app.js
> +    'node_modules/angular/angular.js',
You can remove the ``.js`` :)

2016-11-08 12:34 UTC, drjova commented on invenio_circulation/bundles.py
> +    'node_modules/angular/angular.js',
I see that you use ``requirejs`` to include angular you can remove it from here :)

2016-11-08 12:34 UTC, drjova commented on invenio_circulation/bundles.py
> +    'node_modules/requirejs/require.js',
IMHO we don't need it here

2016-11-08 13:51 UTC, drjova approved these changes

2016-11-08 16:50 UTC, egabancho commented on invenio_circulation/receivers.py
> +            RecordIndexer().index(item)
I would move this changes to a different commit, it might help in the future

2016-11-09 12:52 UTC, mvesper commented on invenio_circulation/receivers.py
> +            RecordIndexer().index(item)
done :)
https://github.com/inveniosoftware/invenio-circulation/pull/60

2016-11-09 16:06 UTC, egabancho commented
Once you rebase on top of https://github.com/inveniosoftware/invenio-circulation/pull/60 ... LGTM

2016-11-10 11:57 UTC, david-caro commented
Looks good to me too

2016-11-10 12:27 UTC, jirikuncar commented on examples/app.py
> +            '/hooks/receivers/circulation_cancel/events/')
can you add a comma at the end of line so we have a clean diff next time? (see line 81 in current diff 😉 )

2016-11-10 14:32 UTC, jirikuncar commented on invenio_circulation/static/js/circulation/directives/circulationUserHoldings.js
> +        });
What about the empty response handler?

2016-11-14 13:01 UTC, merged